// The application consumes the same standalone declaration package that plugin
// authors install. Keep this compatibility module so internal imports remain local.
export type {
  AskOracleInput,
  AskOracleResult,
  OracleOdds,
  PluginCommandContext,
  PluginCommandExecutionResult,
  PluginCommandHandler,
  PluginDisposable,
  PluginJsonValue,
  PluginLocalStorage,
  PluginNotification,
  PluginNotificationLevel,
  PluginOracleProvider,
  PluginResultBlock,
  PluginResultBlockType,
  PluginSlashCommandRegistration,
  PluginStatus,
  PluginStatusLevel,
  SceneSetupInput,
  SceneSetupResult,
  SoloistPluginApi,
  SoloistPluginModule,
} from "../../packages/soloist-plugin-sdk";
